application: inapppurchasetestvignesh
version: 1
runtime: php55
api_version: 1

handlers:
- url: /showme\.txt
  static_files: showme.txt
  upload: showme\.txt

- url: /.*
  script: verifyReceipt.php


